// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class GenderData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GenderData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

group():number {
  return this.bb!.readUint8(this.bb_pos);
}

ratio():number {
  return this.bb!.readUint8(this.bb_pos + 1);
}

static sizeOf():number {
  return 2;
}

static createGenderData(builder:flatbuffers.Builder, group: number, ratio: number):flatbuffers.Offset {
  builder.prep(1, 2);
  builder.writeInt8(ratio);
  builder.writeInt8(group);
  return builder.offset();
}

}
