// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Move {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Move {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

move():number {
  return this.bb!.readUint16(this.bb_pos);
}

level():number {
  return this.bb!.readInt8(this.bb_pos + 2);
}

static sizeOf():number {
  return 4;
}

static createMove(builder:flatbuffers.Builder, move: number, level: number):flatbuffers.Offset {
  builder.prep(2, 4);
  builder.pad(1);
  builder.writeInt8(level);
  builder.writeInt16(move);
  return builder.offset();
}

}
