// automatically generated by the FlatBuffers compiler, do not modify

export { EvoData } from './evo-data.js';
export { GenderData } from './gender-data.js';
export { Hatch } from './hatch.js';
export { Move } from './move.js';
export { PersonalData } from './personal-data.js';
export { PersonalTable } from './personal-table.js';
export { SpeciesInfo } from './species-info.js';
export { StatInfo } from './stat-info.js';
export { ZukanData } from './zukan-data.js';
